package xforms2xaml;

import java.io.IOException;
import javax.swing.JFileChooser;
import javax.xml.transform.TransformerException;

/**
 * JFrame which loads an XHTML document opened by the user, validates it against
 * an XSD schema and transforms it into a XAML document.
 *
 * @author sittova
 */
public class XForms2XAMLTransformerUI extends javax.swing.JFrame {

	//Initialize a new custom transformer.
	private static final XFormsTransformer TRANSFORMER = new XFormsTransformer();

	/**
	 * Creates new form XFormsTransformerUI
	 */
	public XForms2XAMLTransformerUI() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        xFormsFilenameInput = new javax.swing.JTextField();
        xFormsFilenameChooseButton = new javax.swing.JButton();
        validateButton = new javax.swing.JButton();
        transformButton = new javax.swing.JButton();
        messageAreaLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        messageArea = new javax.swing.JTextArea();
        xamlFilenameInput = new javax.swing.JTextField();
        xamlFilenameChooseButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("xforms2xaml/Bundle"); // NOI18N
        setTitle(bundle.getString("windowTitle")); // NOI18N
        setResizable(false);

        xFormsFilenameInput.setText(bundle.getString("XForms2XAMLTransformerUI.xFormsFilenameInput.text")); // NOI18N

        xFormsFilenameChooseButton.setText(bundle.getString("XFormsValidatorUI.inputFileButton.text")); // NOI18N
        xFormsFilenameChooseButton.setName("inputFileButton"); // NOI18N
        xFormsFilenameChooseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xFormsFilenameChooseButtonActionPerformed(evt);
            }
        });

        validateButton.setText(bundle.getString("XFormsValidatorUI.text")); // NOI18N
        validateButton.setName(""); // NOI18N
        validateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validateButtonActionPerformed(evt);
            }
        });

        transformButton.setText(bundle.getString("XForms2XAMLTransformerUI.transformButton.text")); // NOI18N
        transformButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transformButtonActionPerformed(evt);
            }
        });

        messageAreaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        messageAreaLabel.setText(bundle.getString("XForms2XAMLTransformerUI.messageAreaLabel.text")); // NOI18N

        messageArea.setColumns(20);
        messageArea.setRows(5);
        jScrollPane1.setViewportView(messageArea);

        xamlFilenameInput.setText(bundle.getString("XForms2XAMLTransformerUI.xamlFilenameInput.text")); // NOI18N

        xamlFilenameChooseButton.setText(bundle.getString("XForms2XAMLTransformerUI.xamlFilenameChooseButton.text")); // NOI18N
        xamlFilenameChooseButton.setToolTipText(bundle.getString("XForms2XAMLTransformerUI.xamlFilenameChooseButton.toolTipText")); // NOI18N
        xamlFilenameChooseButton.setName("inputFileButton"); // NOI18N
        xamlFilenameChooseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xamlFilenameChooseButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(messageAreaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(xamlFilenameChooseButton, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                    .addComponent(xFormsFilenameChooseButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(xFormsFilenameInput, javax.swing.GroupLayout.DEFAULT_SIZE, 678, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(159, 159, 159)
                                .addComponent(validateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(transformButton, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(85, 85, 85))
                            .addComponent(jScrollPane1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(xamlFilenameInput, javax.swing.GroupLayout.DEFAULT_SIZE, 678, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(xFormsFilenameChooseButton)
                    .addComponent(xFormsFilenameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(xamlFilenameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(xamlFilenameChooseButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(validateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(transformButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(messageAreaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
	 * A button action that lets a user choose a file from their file system.
	 *
	 * @param evt event that triggers this code
	 */
    private void xFormsFilenameChooseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xFormsFilenameChooseButtonActionPerformed
		//JFileChooser provides a simple mechanism for the user to choose a file.
		JFileChooser chooser = new JFileChooser();
		//Pops up an "Open File" file chooser dialog.
		if (chooser.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
			//Set a text in the message area to read the filepath.
			xFormsFilenameInput.setText(chooser.getSelectedFile().getAbsolutePath());
		}
    }//GEN-LAST:event_xFormsFilenameChooseButtonActionPerformed
	/**
	 * A button action that validates an input XHTML file against an XSD schema.
	 *
	 * @param evt event that triggers this code
	 * @throws IOException
	 */
    private void validateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validateButtonActionPerformed
		//Get the name of the input XForms file from the textbox.
		String xFormsFilename = xFormsFilenameInput.getText();

		//If the textbox does not contain a name of the input XForms file, prompt the user.
		if (xFormsFilename.isEmpty()) {
			//Adds a prompting message into the message area in the GUI.
			addMessage("Choose an XForms input file.");
			//The textbox is not empty, continue with the validation.
		} else {
			//Try validating the input file.
			try {
				//Add a message about success/failure into the message area in the GUI.
				addMessage("The input XForms file is " + (TRANSFORMER.validate(xFormsFilename) ? "" : "not ") + "valid.");
			} catch (IOException ex) {
				//If an exception is thrown, catch it and log it.
				addMessage("Input XForms file does not exist.");
			}
		}
    }//GEN-LAST:event_validateButtonActionPerformed
	/**
	 * A button action that transforms an input XHTML file into a XAML file.
	 *
	 * @param evt event that triggers this code
	 * @throws IOException, TransformerException
	 */
    private void transformButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transformButtonActionPerformed
		//Read the name of the input XHTML file.
		String xFormsFilename = xFormsFilenameInput.getText();
		//Read the name of the output XAML file.
		String xamlFilename = xamlFilenameInput.getText();

		//If the textbox does not contain a name of the input XForms file, prompt the user.
		if (xFormsFilename.isEmpty()) {
			//Adds a prompting message into the message area in the GUI.
			addMessage("Choose an XForms input file.");
			//If the textbox does not contain a name of the output XAML file, prompt the user.
		} else if (xamlFilename.isEmpty()) {
			//Adds a prompting message into the message area in the GUI.
			addMessage("Choose an XAML output file.");
			//Both textboxes contain filenames, continue with the transformation.
		} else {
			try {
				//Check if the input file is valid before proceeding with the transformation -
				//the user may have decided to skip the manual validation.
				if (TRANSFORMER.validate(xFormsFilename)) {
					//Transform a valid XForms file into an output XAML file.
					TRANSFORMER.transformToXAML(xFormsFilename, xamlFilename);
					//Add a message about completed transformation into the message area in the GUI.
					addMessage("Transformation completed.");
				} else {
					//The input file is invalid, add this message in the message area.
					addMessage("Input XForms file is invalid.");
				}
			} catch (IOException ex) {
				//The input file does not exist, add this message in the message area.
				addMessage("Input XForms file does not exist.");
			} catch (TransformerException ex) {
				//An unexpected error has occurred, add it in the message area.
				addMessage(ex.getMessage());
			}
		}
    }//GEN-LAST:event_transformButtonActionPerformed
	/**
	 * A button action that opens a file chosen by the user.
	 *
	 * @param evt event that triggers this code
	 */
    private void xamlFilenameChooseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xamlFilenameChooseButtonActionPerformed
		//JFileChooser provides a simple mechanism for the user to choose a file.
		JFileChooser chooser = new JFileChooser();
		//Pops up an "Open File" file chooser dialog.
		if (chooser.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
			//If the user confirms opening the file, set a text in the message area to read the filepath.
			xamlFilenameInput.setText(chooser.getSelectedFile().getAbsolutePath());
		}
    }//GEN-LAST:event_xamlFilenameChooseButtonActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(XForms2XAMLTransformerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(XForms2XAMLTransformerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(XForms2XAMLTransformerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(XForms2XAMLTransformerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new XForms2XAMLTransformerUI().setVisible(true);
			}
		});
	}

	/**
	 * Adds the text into the message area in the GUI.
	 *
	 * @param message the text to be printed in the message area of the GUI
	 */
	protected void addMessage(String message) {
		//Set the text of the message area in the GUI.
		messageArea.setText(messageArea.getText() + message + "\n");
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea messageArea;
    private javax.swing.JLabel messageAreaLabel;
    private javax.swing.JButton transformButton;
    private javax.swing.JButton validateButton;
    private javax.swing.JButton xFormsFilenameChooseButton;
    private javax.swing.JTextField xFormsFilenameInput;
    private javax.swing.JButton xamlFilenameChooseButton;
    private javax.swing.JTextField xamlFilenameInput;
    // End of variables declaration//GEN-END:variables
}
